config_version: "2023-09-25"
schema_list:
  - schema: rime_ice

menu:
  page_size: 9

switcher:
  caption: 选择方案
  hotkeys:
    - F4
    - Control+grave
    - Control+Shift+grave
  save_options:
    - ascii_punct
    - traditionalization
    - emoji
    - full_shape
  fold_options: true
  abbreviate_options: true
  option_list_separator: " / "

ascii_composer:
  good_old_caps_lock: false
  switch_key:
    Caps_Lock: commit_code
    Shift_L: noop
    Shift_R: noop
    Control_L: noop
    Control_R: noop

punctuator:
  full_shape:
    " ": { commit: "　" }
    ",": { commit: ， }
    ".": { commit: 。 }
    "<": [《, 〈, «, ‹]
    ">": [》, 〉, », ›]
    "/": [／, ÷]
    "?": { commit: ？ }
    ";": { commit: ； }
    ":": { commit: ： }
    "'": { pair: ["‘", "’"] }
    '"': { pair: ["“", "”"] }
    '\': [、, ＼]
    "|": [·, ｜, "§", "¦"]
    "`": ｀
    "~": ～
    "!": { commit: ！ }
    "@": [＠, ☯]
    "#": [＃, ⌘]
    "%": [％, "°", "℃"]
    "$": [￥, "$", "€", "£", "¥", "¢", "¤"]
    "^": { commit: …… }
    "&": ＆
    "*": [＊, ·, ・, ×, ※, ❂]
    "(": （
    ")": ）
    "-": －
    "_": ——
    "+": ＋
    "=": ＝
    "[": [「, 【, 〔, ［]
    "]": [」, 】, 〕, ］]
    "{": [『, 〖, ｛]
    "}": [』, 〗, ｝]
  half_shape:
    ",": "，"
    ".": "。"
    "<": "《"
    ">": "》"
    "/": "/"
    "?": "？"
    ";": "；"
    ":": "："
    "'": { pair: ["‘", "’"] }
    '"': { pair: ["“", "”"] }
    '\': "、"
    "|": "|"
    "`": "`"
    "~": "~"
    "!": "！"
    "@": "@"
    "#": "#"
    "%": "%"
    "$": "¥"
    "^": "……"
    "&": "&"
    "*": "*"
    "(": "（"
    ")": "）"
    "-": "-"
    "_": ——
    "+": "+"
    "=": "="
    "[": "【"
    "]": "】"
    "{": "「"
    "}": "」"

recognizer:
  patterns:
    email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
    uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"
    url: "^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$" # 自带的，URL 正则
    url_2: "^[A-Za-z]+[.].*"
    colon: "^[A-Za-z]+:.*"
    underscore: "^[A-Za-z]+_.*"

key_binder:
  bindings:
    - { when: composing, accept: Shift+Tab, send: Shift+Left }
    - { when: composing, accept: Tab, send: Shift+Right }
    - { when: composing, accept: Alt+Left, send: Shift+Left }
    - { when: composing, accept: Alt+Right, send: Shift+Right }
    - { when: has_menu, accept: minus, send: Page_Up }
    - { when: has_menu, accept: equal, send: Page_Down }

  optimized_mode_switch:
    - { when: always, accept: Control+comma, toggle: full_shape }
    - { when: always, accept: Control+period, toggle: ascii_punct }
    - { when: always, accept: Control+slash, toggle: traditionalization }
